alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias g='git'
alias gl='git log --oneline'
alias gs='git status'
alias nvim='/snap/bin/nvim'
alias h='$(better_history)'

alias d='docker'
alias dit='docker exec -it'
alias dc='docker compose'
